/********************************************************************
* BtuMCPrinterCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BtuMCPrinterCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableBtuMCPrinterCint();
extern void G__cpp_setup_inheritanceBtuMCPrinterCint();
extern void G__cpp_setup_typetableBtuMCPrinterCint();
extern void G__cpp_setup_memvarBtuMCPrinterCint();
extern void G__cpp_setup_globalBtuMCPrinterCint();
extern void G__cpp_setup_memfuncBtuMCPrinterCint();
extern void G__cpp_setup_funcBtuMCPrinterCint();
extern void G__set_cpp_environmentBtuMCPrinterCint();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "BtuMCPrinter.hh"
#include "BtuPdt.hh"
#include "BtuRootFile.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BtuMCPrinterCintLN_string;
extern G__linked_taginfo G__BtuMCPrinterCintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TTree;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TBranch;
extern G__linked_taginfo G__BtuMCPrinterCintLN_maplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_BtuRootFile;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__BtuMCPrinterCintLN_TVector3;
extern G__linked_taginfo G__BtuMCPrinterCintLN_BtuMCPrinter;
extern G__linked_taginfo G__BtuMCPrinterCintLN_BtuPdt;

/* STUB derived class for protected member access */
