//
// File generated by /afs/slac.stanford.edu/g/babar/package/root/5.10-00f/Linux24SL3_i386_gcc323/bin/rootcint at Thu Apr 12 20:25:37 2007

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BtuMCPrinterCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TCollectionProxy.h"
#include "TIsAProxy.h"
// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void BtuRootFile_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void BtuRootFile_Dictionary();
   static void *new_BtuRootFile(void *p = 0);
   static void *newArray_BtuRootFile(Long_t size, void *p);
   static void delete_BtuRootFile(void *p);
   static void deleteArray_BtuRootFile(void *p);
   static void destruct_BtuRootFile(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::BtuRootFile*)
   {
      ::BtuRootFile *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BtuRootFile),0);
      static ::ROOT::TGenericClassInfo 
         instance("BtuRootFile", "../BtuMCPrinter/BtuRootFile.hh", 15,
                  typeid(::BtuRootFile), DefineBehavior(ptr, ptr),
                  0, &BtuRootFile_Dictionary, isa_proxy, 0,
                  sizeof(::BtuRootFile) );
      instance.SetNew(&new_BtuRootFile);
      instance.SetNewArray(&newArray_BtuRootFile);
      instance.SetDelete(&delete_BtuRootFile);
      instance.SetDeleteArray(&deleteArray_BtuRootFile);
      instance.SetDestructor(&destruct_BtuRootFile);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::BtuRootFile*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BtuRootFile_Dictionary() {
      ::ROOT::GenerateInitInstance((const ::BtuRootFile*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void BtuMCPrinter_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void BtuMCPrinter_Dictionary();
   static void *new_BtuMCPrinter(void *p = 0);
   static void *newArray_BtuMCPrinter(Long_t size, void *p);
   static void delete_BtuMCPrinter(void *p);
   static void deleteArray_BtuMCPrinter(void *p);
   static void destruct_BtuMCPrinter(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::BtuMCPrinter*)
   {
      ::BtuMCPrinter *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BtuMCPrinter),0);
      static ::ROOT::TGenericClassInfo 
         instance("BtuMCPrinter", "BtuMCPrinter.hh", 9,
                  typeid(::BtuMCPrinter), DefineBehavior(ptr, ptr),
                  0, &BtuMCPrinter_Dictionary, isa_proxy, 0,
                  sizeof(::BtuMCPrinter) );
      instance.SetNew(&new_BtuMCPrinter);
      instance.SetNewArray(&newArray_BtuMCPrinter);
      instance.SetDelete(&delete_BtuMCPrinter);
      instance.SetDeleteArray(&deleteArray_BtuMCPrinter);
      instance.SetDestructor(&destruct_BtuMCPrinter);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::BtuMCPrinter*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BtuMCPrinter_Dictionary() {
      ::ROOT::GenerateInitInstance((const ::BtuMCPrinter*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void BtuPdt_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void BtuPdt_Dictionary();
   static void *new_BtuPdt(void *p = 0);
   static void *newArray_BtuPdt(Long_t size, void *p);
   static void delete_BtuPdt(void *p);
   static void deleteArray_BtuPdt(void *p);
   static void destruct_BtuPdt(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::BtuPdt*)
   {
      ::BtuPdt *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BtuPdt),0);
      static ::ROOT::TGenericClassInfo 
         instance("BtuPdt", "BtuPdt.hh", 10,
                  typeid(::BtuPdt), DefineBehavior(ptr, ptr),
                  0, &BtuPdt_Dictionary, isa_proxy, 0,
                  sizeof(::BtuPdt) );
      instance.SetNew(&new_BtuPdt);
      instance.SetNewArray(&newArray_BtuPdt);
      instance.SetDelete(&delete_BtuPdt);
      instance.SetDeleteArray(&deleteArray_BtuPdt);
      instance.SetDestructor(&destruct_BtuPdt);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::BtuPdt*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BtuPdt_Dictionary() {
      ::ROOT::GenerateInitInstance((const ::BtuPdt*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_BtuRootFile(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BtuRootFile : new ::BtuRootFile;
   }
   static void *newArray_BtuRootFile(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BtuRootFile[nElements] : new ::BtuRootFile[nElements];
   }
   // Wrapper around operator delete
   static void delete_BtuRootFile(void *p) {
      delete ((::BtuRootFile*)p);
   }
   static void deleteArray_BtuRootFile(void *p) {
      delete [] ((::BtuRootFile*)p);
   }
   static void destruct_BtuRootFile(void *p) {
      typedef ::BtuRootFile current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::BtuRootFile

namespace ROOT {
   // Wrappers around operator new
   static void *new_BtuMCPrinter(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BtuMCPrinter : new ::BtuMCPrinter;
   }
   static void *newArray_BtuMCPrinter(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BtuMCPrinter[nElements] : new ::BtuMCPrinter[nElements];
   }
   // Wrapper around operator delete
   static void delete_BtuMCPrinter(void *p) {
      delete ((::BtuMCPrinter*)p);
   }
   static void deleteArray_BtuMCPrinter(void *p) {
      delete [] ((::BtuMCPrinter*)p);
   }
   static void destruct_BtuMCPrinter(void *p) {
      typedef ::BtuMCPrinter current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::BtuMCPrinter

namespace ROOT {
   // Wrappers around operator new
   static void *new_BtuPdt(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BtuPdt : new ::BtuPdt;
   }
   static void *newArray_BtuPdt(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BtuPdt[nElements] : new ::BtuPdt[nElements];
   }
   // Wrapper around operator delete
   static void delete_BtuPdt(void *p) {
      delete ((::BtuPdt*)p);
   }
   static void deleteArray_BtuPdt(void *p) {
      delete [] ((::BtuPdt*)p);
   }
   static void destruct_BtuPdt(void *p) {
      typedef ::BtuPdt current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::BtuPdt

/********************************************************
* BtuMCPrinterCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableBtuMCPrinterCint();

extern "C" void G__set_cpp_environmentBtuMCPrinterCint() {
  G__add_macro("G__CINTVERSION=50160007");
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("BtuMCPrinter.hh");
  G__add_compiledheader("BtuPdt.hh");
  G__add_compiledheader("BtuRootFile.hh");
  G__cpp_reset_tagtableBtuMCPrinterCint();
}
#include <new>
extern "C" int G__cpp_dllrevBtuMCPrinterCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BtuRootFile */
static int G__BtuMCPrinterCint_211_1_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BtuRootFile* p = NULL;
   long gvp = G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new BtuRootFile((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) BtuRootFile((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == G__PVOID) || (gvp == 0)) {
         p = new BtuRootFile[n];
       } else {
         p = new((void*) gvp) BtuRootFile[n];
       }
     } else {
       if ((gvp == G__PVOID) || (gvp == 0)) {
         p = new BtuRootFile;
       } else {
         p = new((void*) gvp) BtuRootFile;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuRootFile);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BtuMCPrinterCint_211_2_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BtuRootFile*) G__getstructoffset())->Cut((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BtuMCPrinterCint_211_3_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BtuRootFile*) G__getstructoffset())->GetEntry((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BtuMCPrinterCint_211_4_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letLonglong(result7, 110, (G__int64) ((BtuRootFile*) G__getstructoffset())->LoadTree((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BtuMCPrinterCint_211_5_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BtuRootFile*) G__getstructoffset())->Init((TTree*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BtuMCPrinterCint_211_6_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BtuRootFile*) G__getstructoffset())->Loop();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BtuMCPrinterCint_211_7_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BtuRootFile*) G__getstructoffset())->Notify());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BtuMCPrinterCint_211_8_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((BtuRootFile*) G__getstructoffset())->Show((Long64_t) G__Longlong(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((BtuRootFile*) G__getstructoffset())->Show();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BtuMCPrinterCint_211_9_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BtuRootFile* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BtuRootFile(*(BtuRootFile*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuRootFile);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BtuRootFile G__TBtuRootFile;
static int G__BtuMCPrinterCint_211_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   long gvp = G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == G__PVOID) {
       delete[] (BtuRootFile*) soff;
     } else {
       G__setgvp(G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BtuRootFile*) (soff+(sizeof(BtuRootFile)*i)))->~G__TBtuRootFile();
       }
       G__setgvp(gvp);
     }
   } else {
     if (gvp == G__PVOID) {
       delete (BtuRootFile*) soff;
     } else {
       G__setgvp(G__PVOID);
       ((BtuRootFile*) (soff))->~G__TBtuRootFile();
       G__setgvp(gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BtuMCPrinterCint_211_1_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BtuRootFile* dest = (BtuRootFile*) G__getstructoffset();
   *dest = *(BtuRootFile*) libp->para[0].ref;
   const BtuRootFile& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* BtuMCPrinter */
static int G__BtuMCPrinterCint_252_1_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BtuMCPrinter* p = NULL;
   long gvp = G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new BtuMCPrinter((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) BtuMCPrinter((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == G__PVOID) || (gvp == 0)) {
         p = new BtuMCPrinter[n];
       } else {
         p = new((void*) gvp) BtuMCPrinter[n];
       }
     } else {
       if ((gvp == G__PVOID) || (gvp == 0)) {
         p = new BtuMCPrinter;
       } else {
         p = new((void*) gvp) BtuMCPrinter;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuMCPrinter);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BtuMCPrinterCint_252_2_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BtuMCPrinter*) G__getstructoffset())->printEvent((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BtuMCPrinterCint_252_3_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BtuMCPrinter*) G__getstructoffset())->printTree();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BtuMCPrinterCint_252_4_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BtuMCPrinter*) G__getstructoffset())->printTree((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BtuMCPrinterCint_252_5_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BtuMCPrinter*) G__getstructoffset())->printTree((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BtuMCPrinterCint_252_7_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BtuMCPrinter* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BtuMCPrinter(*(BtuMCPrinter*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuMCPrinter);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BtuMCPrinter G__TBtuMCPrinter;
static int G__BtuMCPrinterCint_252_8_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   long gvp = G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == G__PVOID) {
       delete[] (BtuMCPrinter*) soff;
     } else {
       G__setgvp(G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BtuMCPrinter*) (soff+(sizeof(BtuMCPrinter)*i)))->~G__TBtuMCPrinter();
       }
       G__setgvp(gvp);
     }
   } else {
     if (gvp == G__PVOID) {
       delete (BtuMCPrinter*) soff;
     } else {
       G__setgvp(G__PVOID);
       ((BtuMCPrinter*) (soff))->~G__TBtuMCPrinter();
       G__setgvp(gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BtuMCPrinterCint_252_9_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BtuMCPrinter* dest = (BtuMCPrinter*) G__getstructoffset();
   *dest = *(BtuMCPrinter*) libp->para[0].ref;
   const BtuMCPrinter& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* BtuPdt */
static int G__BtuMCPrinterCint_253_1_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BtuPdt* p = NULL;
   long gvp = G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new BtuPdt[n];
     } else {
       p = new((void*) gvp) BtuPdt[n];
     }
   } else {
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new BtuPdt;
     } else {
       p = new((void*) gvp) BtuPdt;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuPdt);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BtuMCPrinterCint_253_2_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((BtuPdt*) G__getstructoffset())->getName((int) G__int(libp->para[0]));
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BtuMCPrinterCint_253_3_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BtuPdt* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BtuPdt(*(BtuPdt*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuPdt);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BtuPdt G__TBtuPdt;
static int G__BtuMCPrinterCint_253_4_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   long gvp = G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == G__PVOID) {
       delete[] (BtuPdt*) soff;
     } else {
       G__setgvp(G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BtuPdt*) (soff+(sizeof(BtuPdt)*i)))->~G__TBtuPdt();
       }
       G__setgvp(gvp);
     }
   } else {
     if (gvp == G__PVOID) {
       delete (BtuPdt*) soff;
     } else {
       G__setgvp(G__PVOID);
       ((BtuPdt*) (soff))->~G__TBtuPdt();
       G__setgvp(gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BtuMCPrinterCint_253_5_0(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BtuPdt* dest = (BtuPdt*) G__getstructoffset();
   const BtuPdt& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BtuRootFile */

/* BtuMCPrinter */

/* BtuPdt */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBtuMCPrinterCint {
 public:
  G__Sizep2memfuncBtuMCPrinterCint() {p=&G__Sizep2memfuncBtuMCPrinterCint::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBtuMCPrinterCint::*p)();
};

size_t G__get_sizep2memfuncBtuMCPrinterCint()
{
  G__Sizep2memfuncBtuMCPrinterCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBtuMCPrinterCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuMCPrinter))) {
     BtuMCPrinter *G__Lderived;
     G__Lderived=(BtuMCPrinter*)0x1000;
     {
       BtuRootFile *G__Lpbase=(BtuRootFile*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuMCPrinter),G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuRootFile),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBtuMCPrinterCint() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<void*,Version_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_maplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<void*,short>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_maplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<void*,short,less<void*>>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_maplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BtuRootFile */
static void G__setup_memvarBtuRootFile(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuRootFile));
   { BtuRootFile *p; p=(BtuRootFile*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->fCurrent)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fCurrent=",0,"!current Tree number in a TChain");
   G__memvar_setup((void*)((long)(&p->runNumber)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"runNumber=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->platform)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"platform=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->partition)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"partition=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->upperID)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"upperID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lowerID)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"lowerID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->majorID)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"majorID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->date)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"date=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->eePx)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"eePx=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->eePy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"eePy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->eePz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"eePz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->eeE)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"eeE=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beamSX)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"beamSX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beamSY)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"beamSY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beamSZ)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"beamSZ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beamSCovXX)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"beamSCovXX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beamSCovYY)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"beamSCovYY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beamSCovZZ)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"beamSCovZZ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beamSCovXZ)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"beamSCovXZ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mcLen)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"mcLen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mcLund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"mcLund[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->mothIdx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"mothIdx[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->dauLen)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"dauLen[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->dauIdx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"dauIdx[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->mcmass)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"mcmass[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->mcp3CM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"mcp3CM[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->mccosthCM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"mccosthCM[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->mcphiCM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"mcphiCM[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->mcp3)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"mcp3[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->mccosth)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"mccosth[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->mcphi)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"mcphi[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->mcVtxx)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"mcVtxx[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->mcVtxy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"mcVtxy[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->mcVtxz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"mcVtxz[1000]=",0,"[mcLen]");
   G__memvar_setup((void*)((long)(&p->nDst2640)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nDst2640=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Dst2640Chi2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640Chi2[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640Doca)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640Doca[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640DocaErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640DocaErr[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640Doca_z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640Doca_z[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640Doca_zErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640Doca_zErr[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640Mass)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640Mass[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640MassErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640MassErr[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640Poca_x)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640Poca_x[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640Poca_y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640Poca_y[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640Poca_z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640Poca_z[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640Vtxx)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640Vtxx[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640Vtxy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640Vtxy[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640Vtxz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640Vtxz[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640costh)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640costh[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640costhCM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640costhCM[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640p3)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640p3[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640p3CM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640p3CM[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640phi)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640phi[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640phiCM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dst2640phiCM[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640Lund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dst2640Lund[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640MCIdx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dst2640MCIdx[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640VtxStatus)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dst2640VtxStatus[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640nDof)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dst2640nDof[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640d1Lund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dst2640d1Lund[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640d1Idx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dst2640d1Idx[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640d2Lund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dst2640d2Lund[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640d2Idx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dst2640d2Idx[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640d3Lund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dst2640d3Lund[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->Dst2640d3Idx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dst2640d3Idx[1000]=",0,"[nDst2640]");
   G__memvar_setup((void*)((long)(&p->nDstar)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nDstar=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->DstarChi2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarChi2[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarDoca)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarDoca[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarDocaErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarDocaErr[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarDoca_z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarDoca_z[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarDoca_zErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarDoca_zErr[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarMass)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarMass[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarMassErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarMassErr[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarPoca_x)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarPoca_x[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarPoca_y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarPoca_y[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarPoca_z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarPoca_z[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarVtxx)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarVtxx[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarVtxy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarVtxy[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarVtxz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarVtxz[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->Dstarcosth)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dstarcosth[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarcosthCM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarcosthCM[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->Dstarp3)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dstarp3[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->Dstarp3CM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dstarp3CM[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->Dstarphi)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Dstarphi[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarphiCM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"DstarphiCM[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarLund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"DstarLund[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarMCIdx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"DstarMCIdx[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarVtxStatus)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"DstarVtxStatus[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->DstarnDof)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"DstarnDof[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->Dstard1Lund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dstard1Lund[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->Dstard1Idx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dstard1Idx[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->Dstard2Lund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dstard2Lund[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->Dstard2Idx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Dstard2Idx[1000]=",0,"[nDstar]");
   G__memvar_setup((void*)((long)(&p->nD0)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nD0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->D0Chi2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0Chi2[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0Doca)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0Doca[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0DocaErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0DocaErr[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0Doca_z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0Doca_z[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0Doca_zErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0Doca_zErr[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0FlightBSCosA)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0FlightBSCosA[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0FlightBSErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0FlightBSErr[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0FlightBSLen)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0FlightBSLen[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0FlightCosA)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0FlightCosA[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0FlightErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0FlightErr[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0FlightLen)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0FlightLen[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0Mass)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0Mass[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0MassErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0MassErr[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0Poca_x)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0Poca_x[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0Poca_y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0Poca_y[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0Poca_z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0Poca_z[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0Vtxx)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0Vtxx[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0Vtxy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0Vtxy[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0Vtxz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0Vtxz[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0costh)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0costh[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0costhCM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0costhCM[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0p3)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0p3[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0p3CM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0p3CM[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0phi)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0phi[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0phiCM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"D0phiCM[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0Lund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"D0Lund[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0MCIdx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"D0MCIdx[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0VtxStatus)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"D0VtxStatus[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0nDof)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"D0nDof[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0d1Lund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"D0d1Lund[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0d1Idx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"D0d1Idx[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0d2Lund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"D0d2Lund[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->D0d2Idx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"D0d2Idx[1000]=",0,"[nD0]");
   G__memvar_setup((void*)((long)(&p->nPi)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nPi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PiDoca)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"PiDoca[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->PiDocaErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"PiDocaErr[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->PiDoca_z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"PiDoca_z[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->PiDoca_zErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"PiDoca_zErr[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->PiPoca_x)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"PiPoca_x[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->PiPoca_y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"PiPoca_y[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->PiPoca_z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"PiPoca_z[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->Picosth)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Picosth[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->PicosthCM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"PicosthCM[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->Pip3)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Pip3[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->Pip3CM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Pip3CM[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->Piphi)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Piphi[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->PiphiCM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"PiphiCM[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->PiLund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"PiLund[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->PiMCIdx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"PiMCIdx[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->PiTrkIdx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"PiTrkIdx[1000]=",0,"[nPi]");
   G__memvar_setup((void*)((long)(&p->nK)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nK=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->KDoca)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"KDoca[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->KDocaErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"KDocaErr[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->KDoca_z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"KDoca_z[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->KDoca_zErr)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"KDoca_zErr[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->KPoca_x)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"KPoca_x[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->KPoca_y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"KPoca_y[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->KPoca_z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"KPoca_z[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->Kcosth)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Kcosth[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->KcosthCM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"KcosthCM[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->Kp3)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Kp3[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->Kp3CM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Kp3CM[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->Kphi)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Kphi[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->KphiCM)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"KphiCM[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->KLund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"KLund[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->KMCIdx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"KMCIdx[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->KTrkIdx)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"KTrkIdx[1000]=",0,"[nK]");
   G__memvar_setup((void*)((long)(&p->nTRK)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nTRK=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TRKLund)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TRKLund[1000]=",0,"[nTRK]");
   G__memvar_setup((void*)((long)(&p->TRKnSvt)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TRKnSvt[1000]=",0,"[nTRK]");
   G__memvar_setup((void*)((long)(&p->TRKnDch)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TRKnDch[1000]=",0,"[nTRK]");
   G__memvar_setup((void*)((long)(&p->TRKnHit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TRKnHit[1000]=",0,"[nTRK]");
   G__memvar_setup((void*)((long)(&p->piSelectorsMap)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"piSelectorsMap[1000]=",0,"[nTRK]");
   G__memvar_setup((void*)((long)(&p->b_runNumber)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_runNumber=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_platform)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_platform=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_partition)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_partition=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_upperID)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_upperID=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_lowerID)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_lowerID=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_majorID)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_majorID=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_date)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_date=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_eePx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_eePx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_eePy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_eePy=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_eePz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_eePz=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_eeE)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_eeE=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_beamSX)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_beamSX=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_beamSY)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_beamSY=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_beamSZ)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_beamSZ=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_beamSCovXX)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_beamSCovXX=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_beamSCovYY)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_beamSCovYY=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_beamSCovZZ)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_beamSCovZZ=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_beamSCovXZ)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_beamSCovXZ=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mcLen)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_mcLen=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mcLund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_mcLund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mothIdx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_mothIdx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dauLen)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_dauLen=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dauIdx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_dauIdx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mcmass)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_mcmass=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mcp3CM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_mcp3CM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mccosthCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_mccosthCM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mcphiCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_mcphiCM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mcp3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_mcp3=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mccosth)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_mccosth=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mcphi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_mcphi=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mcVtxx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_mcVtxx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mcVtxy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_mcVtxy=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mcVtxz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_mcVtxz=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nDst2640)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_nDst2640=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640Chi2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640Chi2=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640Doca)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640Doca=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640DocaErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640DocaErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640Doca_z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640Doca_z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640Doca_zErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640Doca_zErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640Mass)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640Mass=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640MassErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640MassErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640Poca_x)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640Poca_x=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640Poca_y)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640Poca_y=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640Poca_z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640Poca_z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640Vtxx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640Vtxx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640Vtxy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640Vtxy=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640Vtxz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640Vtxz=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640costh)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640costh=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640costhCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640costhCM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640p3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640p3=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640p3CM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640p3CM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640phi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640phi=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640phiCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640phiCM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640Lund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640Lund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640MCIdx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640MCIdx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640VtxStatus)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640VtxStatus=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640nDof)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640nDof=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640d1Lund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640d1Lund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640d1Idx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640d1Idx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640d2Lund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640d2Lund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640d2Idx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640d2Idx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640d3Lund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640d3Lund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dst2640d3Idx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dst2640d3Idx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nDstar)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_nDstar=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarChi2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarChi2=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarDoca)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarDoca=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarDocaErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarDocaErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarDoca_z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarDoca_z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarDoca_zErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarDoca_zErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarMass)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarMass=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarMassErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarMassErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarPoca_x)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarPoca_x=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarPoca_y)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarPoca_y=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarPoca_z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarPoca_z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarVtxx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarVtxx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarVtxy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarVtxy=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarVtxz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarVtxz=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dstarcosth)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dstarcosth=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarcosthCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarcosthCM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dstarp3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dstarp3=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dstarp3CM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dstarp3CM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dstarphi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dstarphi=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarphiCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarphiCM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarLund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarLund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarMCIdx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarMCIdx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarVtxStatus)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarVtxStatus=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_DstarnDof)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_DstarnDof=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dstard1Lund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dstard1Lund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dstard1Idx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dstard1Idx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dstard2Lund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dstard2Lund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Dstard2Idx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Dstard2Idx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nD0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_nD0=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0Chi2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0Chi2=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0Doca)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0Doca=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0DocaErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0DocaErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0Doca_z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0Doca_z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0Doca_zErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0Doca_zErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0FlightBSCosA)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0FlightBSCosA=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0FlightBSErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0FlightBSErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0FlightBSLen)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0FlightBSLen=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0FlightCosA)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0FlightCosA=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0FlightErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0FlightErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0FlightLen)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0FlightLen=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0Mass)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0Mass=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0MassErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0MassErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0Poca_x)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0Poca_x=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0Poca_y)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0Poca_y=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0Poca_z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0Poca_z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0Vtxx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0Vtxx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0Vtxy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0Vtxy=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0Vtxz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0Vtxz=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0costh)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0costh=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0costhCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0costhCM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0p3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0p3=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0p3CM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0p3CM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0phi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0phi=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0phiCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0phiCM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0Lund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0Lund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0MCIdx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0MCIdx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0VtxStatus)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0VtxStatus=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0nDof)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0nDof=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0d1Lund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0d1Lund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0d1Idx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0d1Idx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0d2Lund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0d2Lund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D0d2Idx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_D0d2Idx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nPi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_nPi=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PiDoca)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_PiDoca=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PiDocaErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_PiDocaErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PiDoca_z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_PiDoca_z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PiDoca_zErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_PiDoca_zErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PiPoca_x)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_PiPoca_x=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PiPoca_y)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_PiPoca_y=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PiPoca_z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_PiPoca_z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Picosth)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Picosth=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PicosthCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_PicosthCM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Pip3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Pip3=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Pip3CM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Pip3CM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Piphi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Piphi=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PiphiCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_PiphiCM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PiLund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_PiLund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PiMCIdx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_PiMCIdx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PiTrkIdx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_PiTrkIdx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nK)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_nK=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_KDoca)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_KDoca=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_KDocaErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_KDocaErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_KDoca_z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_KDoca_z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_KDoca_zErr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_KDoca_zErr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_KPoca_x)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_KPoca_x=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_KPoca_y)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_KPoca_y=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_KPoca_z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_KPoca_z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Kcosth)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Kcosth=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_KcosthCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_KcosthCM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Kp3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Kp3=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Kp3CM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Kp3CM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Kphi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_Kphi=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_KphiCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_KphiCM=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_KLund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_KLund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_KMCIdx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_KMCIdx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_KTrkIdx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_KTrkIdx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nTRK)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_nTRK=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TRKLund)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_TRKLund=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TRKnSvt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_TRKnSvt=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TRKnDch)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_TRKnDch=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TRKnHit)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_TRKnHit=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_piSelectorsMap)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch),-1,-1,1,"b_piSelectorsMap=",0,"!");
   G__memvar_setup((void*)NULL,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* BtuMCPrinter */
static void G__setup_memvarBtuMCPrinter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuMCPrinter));
   { BtuMCPrinter *p; p=(BtuMCPrinter*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}


   /* BtuPdt */
static void G__setup_memvarBtuPdt(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuPdt));
   { BtuPdt *p; p=(BtuPdt*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBtuMCPrinterCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBtuRootFile(void) {
   /* BtuRootFile */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuRootFile));
   G__memfunc_setup("BtuRootFile",1103,G__BtuMCPrinterCint_211_1_0, 105, G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuRootFile), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 0 tree", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cut",300,G__BtuMCPrinterCint_211_2_0, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,G__BtuMCPrinterCint_211_3_0, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LoadTree",784,G__BtuMCPrinterCint_211_4_0, 110, -1, G__defined_typename("Long64_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,G__BtuMCPrinterCint_211_5_0, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Loop",410,G__BtuMCPrinterCint_211_6_0, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,G__BtuMCPrinterCint_211_7_0, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Show",417,G__BtuMCPrinterCint_211_8_0, 121, -1, -1, 0, 1, 1, 1, 0, "n - 'Long64_t' 0 -1 entry", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("BtuRootFile", 1103, G__BtuMCPrinterCint_211_9_0, (int) ('i'), G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuRootFile), -1, 0, 1, 1, 1, 0, "u 'BtuRootFile' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BtuRootFile", 1229, G__BtuMCPrinterCint_211_0_1, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BtuMCPrinterCint_211_1_1, (int) ('u'), G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuRootFile), -1, 1, 1, 1, 1, 0, "u 'BtuRootFile' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncBtuMCPrinter(void) {
   /* BtuMCPrinter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuMCPrinter));
   G__memfunc_setup("BtuMCPrinter",1183,G__BtuMCPrinterCint_252_1_0, 105, G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuMCPrinter), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 NULL tree", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("printEvent",1071,G__BtuMCPrinterCint_252_2_0, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - event", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("printTree",957,G__BtuMCPrinterCint_252_3_0, 121, -1, -1, 0, 0, 1, 1, 0, "", "print tree of current event", (void*) NULL, 0);
   G__memfunc_setup("printTree",957,G__BtuMCPrinterCint_252_4_0, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - theTrk i - 'Int_t' 0 - pos", "print tree, ", (void*) NULL, 0);
   G__memfunc_setup("printTree",957,G__BtuMCPrinterCint_252_5_0, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - event i - 'Int_t' 0 - theTrk "
"i - 'Int_t' 0 - pos", "print tree for an event ", (void*) NULL, 0);
   G__memfunc_setup("vectorize",987,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TVector3), -1, 0, 3, 1, 4, 0, 
"f - 'Float_t' 0 - rho f - 'Float_t' 0 - theta "
"f - 'Float_t' 0 - phi", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("BtuMCPrinter", 1183, G__BtuMCPrinterCint_252_7_0, (int) ('i'), G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuMCPrinter), -1, 0, 1, 1, 1, 0, "u 'BtuMCPrinter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BtuMCPrinter", 1309, G__BtuMCPrinterCint_252_8_0, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BtuMCPrinterCint_252_9_0, (int) ('u'), G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuMCPrinter), -1, 1, 1, 1, 1, 0, "u 'BtuMCPrinter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncBtuPdt(void) {
   /* BtuPdt */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuPdt));
   G__memfunc_setup("BtuPdt",595,G__BtuMCPrinterCint_253_1_0, 105, G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuPdt), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getName",705,G__BtuMCPrinterCint_253_2_0, 117, G__get_linked_tagnum(&G__BtuMCPrinterCintLN_string), -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("BtuPdt", 595, G__BtuMCPrinterCint_253_3_0, (int) ('i'), G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuPdt), -1, 0, 1, 1, 1, 0, "u 'BtuPdt' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BtuPdt", 721, G__BtuMCPrinterCint_253_4_0, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BtuMCPrinterCint_253_5_0, (int) ('u'), G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuPdt), -1, 1, 1, 1, 1, 0, "u 'BtuPdt' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBtuMCPrinterCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBtuMCPrinterCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBtuMCPrinterCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BtuMCPrinterCintLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_maplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR = { "map<void*,short,less<void*>,allocator<pair<void* const,short> > >" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_BtuRootFile = { "BtuRootFile" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_BtuMCPrinter = { "BtuMCPrinter" , 99 , -1 };
G__linked_taginfo G__BtuMCPrinterCintLN_BtuPdt = { "BtuPdt" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBtuMCPrinterCint() {
  G__BtuMCPrinterCintLN_string.tagnum = -1 ;
  G__BtuMCPrinterCintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TTree.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TBranch.tagnum = -1 ;
  G__BtuMCPrinterCintLN_maplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_BtuRootFile.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__BtuMCPrinterCintLN_TVector3.tagnum = -1 ;
  G__BtuMCPrinterCintLN_BtuMCPrinter.tagnum = -1 ;
  G__BtuMCPrinterCintLN_BtuPdt.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBtuMCPrinterCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_string);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TTree);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TBranch);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_maplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuRootFile),sizeof(BtuRootFile),-1,1280,(char*)NULL,G__setup_memvarBtuRootFile,G__setup_memfuncBtuRootFile);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum(&G__BtuMCPrinterCintLN_TVector3);
   G__tagtable_setup(G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuMCPrinter),sizeof(BtuMCPrinter),-1,1280,(char*)NULL,G__setup_memvarBtuMCPrinter,G__setup_memfuncBtuMCPrinter);
   G__tagtable_setup(G__get_linked_tagnum(&G__BtuMCPrinterCintLN_BtuPdt),sizeof(BtuPdt),-1,1280,(char*)NULL,G__setup_memvarBtuPdt,G__setup_memfuncBtuPdt);
}
extern "C" void G__cpp_setupBtuMCPrinterCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupBtuMCPrinterCint()");
  G__set_cpp_environmentBtuMCPrinterCint();
  G__cpp_setup_tagtableBtuMCPrinterCint();

  G__cpp_setup_inheritanceBtuMCPrinterCint();

  G__cpp_setup_typetableBtuMCPrinterCint();

  G__cpp_setup_memvarBtuMCPrinterCint();

  G__cpp_setup_memfuncBtuMCPrinterCint();
  G__cpp_setup_globalBtuMCPrinterCint();
  G__cpp_setup_funcBtuMCPrinterCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBtuMCPrinterCint();
  return;
}
class G__cpp_setup_initBtuMCPrinterCint {
  public:
    G__cpp_setup_initBtuMCPrinterCint() { G__add_setup_func("BtuMCPrinterCint",(G__incsetup)(&G__cpp_setupBtuMCPrinterCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBtuMCPrinterCint() { G__remove_setup_func("BtuMCPrinterCint"); }
};
G__cpp_setup_initBtuMCPrinterCint G__cpp_setup_initializerBtuMCPrinterCint;

