//
// File generated by rootcint at Mon Dec 10 21:07:53 2007

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "fileDAWkRa.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TCollectionProxy.h"
#include "TIsAProxy.h"
// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

/********************************************************
* /afs/slac.stanford.edu/u/eb/benitezj/ana42/workdir/SOFTWARE/FUNCTIONS/fileDAWkRa.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablefileDAWkRa();

extern "C" void G__set_cpp_environmentfileDAWkRa() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/afs/slac.stanford.edu/u/eb/benitezj/ana42/workdir/SOFTWARE/FUNCTIONS/SetHisto.C");
  G__cpp_reset_tagtablefileDAWkRa();
}
#include <new>
extern "C" int G__cpp_dllrevfileDAWkRa() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */
static int G__fileDAWkRa__0_396(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SetHisto((TH1F*) G__int(libp->para[0]), *((TString*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]), (Float_t) G__double(libp->para[3])
, (Float_t) G__double(libp->para[4]), *((TString*) G__int(libp->para[5])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fileDAWkRa__0_397(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SetHistoXY(
(TH1F*) G__int(libp->para[0]), *((TString*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]), (Float_t) G__double(libp->para[3])
, (Float_t) G__double(libp->para[4]), *((TString*) G__int(libp->para[5]))
, *((TString*) G__int(libp->para[6])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fileDAWkRa__0_398(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SetHisto2D(
(TH2F*) G__int(libp->para[0]), *((TString*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]), (Float_t) G__double(libp->para[3])
, (Float_t) G__double(libp->para[4]), *((TString*) G__int(libp->para[5]))
, (Int_t) G__int(libp->para[6]), (Float_t) G__double(libp->para[7])
, (Float_t) G__double(libp->para[8]), *((TString*) G__int(libp->para[9]))
, *((TString*) G__int(libp->para[10])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncfileDAWkRa {
 public:
  G__Sizep2memfuncfileDAWkRa() {p=&G__Sizep2memfuncfileDAWkRa::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncfileDAWkRa::*p)();
};

size_t G__get_sizep2memfuncfileDAWkRa()
{
  G__Sizep2memfuncfileDAWkRa a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancefileDAWkRa() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablefileDAWkRa() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__fileDAWkRaLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileDAWkRaLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileDAWkRaLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileDAWkRaLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileDAWkRaLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,Version_t>",117,G__get_linked_tagnum(&G__fileDAWkRaLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,short>",117,G__get_linked_tagnum(&G__fileDAWkRaLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,short,less<void*>>",117,G__get_linked_tagnum(&G__fileDAWkRaLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvarfileDAWkRa() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncfileDAWkRa() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalfileDAWkRa() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
   G__memfunc_setup("SetHisto", 819, G__fileDAWkRa__0_396, 121, -1, -1, 0, 6, 1, 1, 0, 
"U 'TH1F' - 0 - h u 'TString' - 0 - title "
"i - 'Int_t' 0 - nbins f - 'Float_t' 0 - xmin "
"f - 'Float_t' 0 - xmax u 'TString' - 0 - xtitle", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("SetHistoXY", 996, G__fileDAWkRa__0_397, 121, -1, -1, 0, 7, 1, 1, 0, 
"U 'TH1F' - 0 - h u 'TString' - 0 - title "
"i - 'Int_t' 0 - nbins f - 'Float_t' 0 - xmin "
"f - 'Float_t' 0 - xmax u 'TString' - 0 - xtitle "
"u 'TString' - 0 - ytitle", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("SetHisto2D", 937, G__fileDAWkRa__0_398, 121, -1, -1, 0, 11, 1, 1, 0, 
"U 'TH2F' - 0 - h u 'TString' - 0 - title "
"i - 'Int_t' 0 - nxbins f - 'Float_t' 0 - xmin "
"f - 'Float_t' 0 - xmax u 'TString' - 0 - xtitle "
"i - 'Int_t' 0 - nybins f - 'Float_t' 0 - ymin "
"f - 'Float_t' 0 - ymax u 'TString' - 0 - ytitle "
"u 'TString' - 0 - ztitle", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcfileDAWkRa() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__fileDAWkRaLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__fileDAWkRaLN_TH2F = { "TH2F" , 99 , -1 };
G__linked_taginfo G__fileDAWkRaLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__fileDAWkRaLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__fileDAWkRaLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileDAWkRaLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR = { "multimap<void*,short,less<void*>,allocator<pair<void* const,short> > >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablefileDAWkRa() {
  G__fileDAWkRaLN_TH1F.tagnum = -1 ;
  G__fileDAWkRaLN_TH2F.tagnum = -1 ;
  G__fileDAWkRaLN_TString.tagnum = -1 ;
  G__fileDAWkRaLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__fileDAWkRaLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileDAWkRaLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablefileDAWkRa() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__fileDAWkRaLN_TH1F);
   G__get_linked_tagnum(&G__fileDAWkRaLN_TH2F);
   G__get_linked_tagnum(&G__fileDAWkRaLN_TString);
   G__get_linked_tagnum(&G__fileDAWkRaLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__fileDAWkRaLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__fileDAWkRaLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR);
}
extern "C" void G__cpp_setupfileDAWkRa(void) {
  G__check_setup_version(30051515,"G__cpp_setupfileDAWkRa()");
  G__set_cpp_environmentfileDAWkRa();
  G__cpp_setup_tagtablefileDAWkRa();

  G__cpp_setup_inheritancefileDAWkRa();

  G__cpp_setup_typetablefileDAWkRa();

  G__cpp_setup_memvarfileDAWkRa();

  G__cpp_setup_memfuncfileDAWkRa();
  G__cpp_setup_globalfileDAWkRa();
  G__cpp_setup_funcfileDAWkRa();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncfileDAWkRa();
  return;
}
class G__cpp_setup_initfileDAWkRa {
  public:
    G__cpp_setup_initfileDAWkRa() { G__add_setup_func("fileDAWkRa",(G__incsetup)(&G__cpp_setupfileDAWkRa)); G__call_setup_funcs(); }
   ~G__cpp_setup_initfileDAWkRa() { G__remove_setup_func("fileDAWkRa"); }
};
G__cpp_setup_initfileDAWkRa G__cpp_setup_initializerfileDAWkRa;

