/********************************************************************
* /afs/slac.stanford.edu/u/eb/benitezj/ana42/workdir/SOFTWARE/FUNCTIONS/fileDAWkRa.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /afs/slac.stanford.edu/u/eb/benitezj/ana42/workdir/SOFTWARE/FUNCTIONS/fileDAWkRa.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablefileDAWkRa();
extern void G__cpp_setup_inheritancefileDAWkRa();
extern void G__cpp_setup_typetablefileDAWkRa();
extern void G__cpp_setup_memvarfileDAWkRa();
extern void G__cpp_setup_globalfileDAWkRa();
extern void G__cpp_setup_memfuncfileDAWkRa();
extern void G__cpp_setup_funcfileDAWkRa();
extern void G__set_cpp_environmentfileDAWkRa();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "/afs/slac.stanford.edu/u/eb/benitezj/ana42/workdir/SOFTWARE/FUNCTIONS/SetHisto.C"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__fileDAWkRaLN_TH1F;
extern G__linked_taginfo G__fileDAWkRaLN_TH2F;
extern G__linked_taginfo G__fileDAWkRaLN_TString;
extern G__linked_taginfo G__fileDAWkRaLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__fileDAWkRaLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fileDAWkRaLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;

/* STUB derived class for protected member access */
