// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /afs/slac.stanford.edu/u/eb/benitezj/ana42/workdir/./SOFTWARE/CLASSES/BToDstPi/BToDstPiAnalysisControl.C;

#endif
