/********************************************************************
* /afs/slac.stanford.edu/u/eb/benitezj/ana42/workdir/./SOFTWARE/CLASSES/BToDstPi/filepiNIsU.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /afs/slac.stanford.edu/u/eb/benitezj/ana42/workdir/./SOFTWARE/CLASSES/BToDstPi/filepiNIsU.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablefilepiNIsU();
extern void G__cpp_setup_inheritancefilepiNIsU();
extern void G__cpp_setup_typetablefilepiNIsU();
extern void G__cpp_setup_memvarfilepiNIsU();
extern void G__cpp_setup_globalfilepiNIsU();
extern void G__cpp_setup_memfuncfilepiNIsU();
extern void G__cpp_setup_funcfilepiNIsU();
extern void G__set_cpp_environmentfilepiNIsU();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/afs/slac.stanford.edu/u/eb/benitezj/ana42/workdir/./SOFTWARE/CLASSES/BToDstPi/BToDstPiAnalysisControl.C"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__filepiNIsULN_TVectorTlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TVectorTlEdoublegR;
extern G__linked_taginfo G__filepiNIsULN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__filepiNIsULN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__filepiNIsULN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__filepiNIsULN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__filepiNIsULN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G__filepiNIsULN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR;
extern G__linked_taginfo G__filepiNIsULN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR;
extern G__linked_taginfo G__filepiNIsULN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR;
extern G__linked_taginfo G__filepiNIsULN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR;
extern G__linked_taginfo G__filepiNIsULN_reverse_iteratorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__filepiNIsULN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR;
extern G__linked_taginfo G__filepiNIsULN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__filepiNIsULN_reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__filepiNIsULN_RooCacheManagerlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgR;
extern G__linked_taginfo G__filepiNIsULN_listlERooArgSetmUcOallocatorlERooArgSetmUgRsPgR;
extern G__linked_taginfo G__filepiNIsULN_listlERooAbsLValuemUcOallocatorlERooAbsLValuemUgRsPgR;
extern G__linked_taginfo G__filepiNIsULN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__filepiNIsULN_BToDstPiAnalysis;

/* STUB derived class for protected member access */
