#0 pion modes
createkslllists BToKsMuMu SllSeq "B0 -> K_S0 mu+ mu-" "KsDefault XsllMuList XsllMuList"
createklllists BToKMuMu SllSeq   "B+ -> K+ mu+ mu-"   "KLHNotPion XsllMuList XsllMuList"
createkslllists BToKsEE SllSeq   "B0 -> K_S0 e+ e-"   "KsDefault XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createklllists BToKEE SllSeq     "B+ -> K+ e+ e-"     "KLHNotPion XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
#single pion modes
createkslllists BToKsPi0MuMu SllSeq "B0 -> K_S0 pi0 mu+ mu-" "KsDefault pi0DefaultMass XsllMuList XsllMuList"
createklllists BToKPi0MuMu SllSeq   "B+ -> K+ pi0 mu+ mu-"   "KLHNotPion pi0DefaultMass XsllMuList XsllMuList"
createkslllists BToKsPiMuMu SllSeq  "B+ -> K_S0 pi+ mu+ mu-" "KsDefault ChargedTracks XsllMuList XsllMuList"
createklllists BToKPiMuMu SllSeq    "B0 -> K+ pi- mu+ mu-"   "KLHNotPion ChargedTracks XsllMuList XsllMuList"
createkslllists BToKsPi0EE SllSeq   "B0 -> K_S0 pi0 e+ e-"   "KsDefault pi0DefaultMass XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createklllists BToKPi0EE SllSeq     "B+ -> K+ pi0 e+ e-"     "KLHNotPion pi0DefaultMass XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createkslllists BToKsPiEE SllSeq    "B+ -> K_S0 pi+ e+ e-"   "KsDefault ChargedTracks XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createklllists BToKPiEE SllSeq      "B0 -> K+ pi- e+ e-"     "KLHNotPion ChargedTracks XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
#2pion modes
createkslllists BToKsPiPi0MuMu SllSeq "B+ -> K_S0 pi+ pi0 mu+ mu-" "KsDefault ChargedTracks pi0DefaultMass XsllMuList XsllMuList"
createklllists BToKPiPi0MuMu SllSeq   "B0 -> K+ pi- pi0 mu+ mu-"   "KLHNotPion ChargedTracks pi0DefaultMass XsllMuList XsllMuList"
createkslllists BToKsPiPiMuMu SllSeq  "B0 -> K_S0 pi+ pi- mu+ mu-" "KsDefault ChargedTracks ChargedTracks XsllMuList XsllMuList"
createklllists BToKPiPiMuMu SllSeq    "B+ -> K+ pi+ pi- mu+ mu-"   "KLHNotPion ChargedTracks ChargedTracks XsllMuList XsllMuList"
createkslllists BToKsPiPi0EE SllSeq   "B+ -> K_S0 pi+ pi0 e+ e-"   "KsDefault ChargedTracks pi0DefaultMass XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createklllists BToKPiPi0EE SllSeq     "B0 -> K+ pi- pi0 e+ e-"     "KLHNotPion ChargedTracks pi0DefaultMass XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createkslllists BToKsPiPiEE SllSeq    "B0 -> K_S0 pi+ pi- e+ e-"   "KsDefault ChargedTracks ChargedTracks XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createklllists BToKPiPiEE SllSeq      "B+ -> K+ pi+ pi- e+ e-"     "KLHNotPion ChargedTracks ChargedTracks XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
###################3pion modes
createkslllists BToKsPiPiPi0MuMu SllSeq "B0 -> K_S0 pi+ pi- pi0 mu+ mu-" "KsDefault ChargedTracks ChargedTracks pi0DefaultMass XsllMuList XsllMuList"
createklllists BToKPiPiPi0MuMu SllSeq   "B+ -> K+ pi+ pi- pi0 mu+ mu-"   "KLHNotPion ChargedTracks ChargedTracks pi0DefaultMass XsllMuList XsllMuList"
createkslllists BToKsPiPiPiMuMu SllSeq  "B+ -> K_S0 pi+ pi- pi+ mu+ mu-" "KsDefault ChargedTracks ChargedTracks ChargedTracks XsllMuList XsllMuList"
createklllists BToKPiPiPiMuMu SllSeq    "B0 -> K+ pi+ pi- pi- mu+ mu-"   "KLHNotPion ChargedTracks ChargedTracks ChargedTracks XsllMuList XsllMuList"
createkslllists BToKsPiPiPi0EE SllSeq   "B0 -> K_S0 pi+ pi- pi0 e+ e-"   "KsDefault ChargedTracks ChargedTracks pi0DefaultMass XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createklllists BToKPiPiPi0EE SllSeq     "B+ -> K+ pi- pi+ pi0 e+ e-"     "KLHNotPion ChargedTracks ChargedTracks pi0DefaultMass XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createkslllists BToKsPiPiPiEE SllSeq    "B+ -> K_S0 pi+ pi- pi+ e+ e-"   "KsDefault ChargedTracks ChargedTracks ChargedTracks XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createklllists BToKPiPiPiEE SllSeq      "B0 -> K+ pi- pi+ pi- e+ e-"     "KLHNotPion ChargedTracks ChargedTracks ChargedTracks XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"

###################4pion modes
createkslllists BToKsPiPiPiPi0MuMu SllSeq "B+ -> K_S0 pi+ pi- pi+ pi0 mu+ mu-" "KsDefault ChargedTracks ChargedTracks ChargedTracks pi0DefaultMass XsllMuList XsllMuList"
createklllists BToKPiPiPiPi0MuMu SllSeq   "B0 -> K+ pi- pi+ pi- pi0 mu+ mu-"   "KLHNotPion ChargedTracks ChargedTracks ChargedTracks pi0DefaultMass XsllMuList XsllMuList"
createkslllists BToKsPiPiPiPiMuMu SllSeq  "B0 -> K_S0 pi+ pi- pi+ pi- mu+ mu-" "KsDefault ChargedTracks ChargedTracks ChargedTracks ChargedTracks XsllMuList XsllMuList"
createklllists BToKPiPiPiPiMuMu SllSeq    "B+ -> K+ pi+ pi- pi+ pi- mu+ mu-"   "KLHNotPion ChargedTracks ChargedTracks ChargedTracks ChargedTracks XsllMuList XsllMuList"
createkslllists BToKsPiPiPiPi0EE SllSeq   "B+ -> K_S0 pi+ pi- pi+ pi0 e+ e-"   "KsDefault ChargedTracks ChargedTracks ChargedTracks pi0DefaultMass XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createklllists BToKPiPiPiPi0EE SllSeq     "B0 -> K+ pi+ pi- pi- pi0 e+ e-"     "KLHNotPion ChargedTracks ChargedTracks ChargedTracks pi0DefaultMass XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createkslllists BToKsPiPiPiPiEE SllSeq    "B0 -> K_S0 pi+ pi- pi+ pi- e+ e-"   "KsDefault ChargedTracks ChargedTracks ChargedTracks ChargedTracks XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createklllists BToKPiPiPiPiEE SllSeq      "B+ -> K+ pi+ pi- pi+ pi- e+ e-"     "KLHNotPion ChargedTracks ChargedTracks ChargedTracks ChargedTracks XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"

#############dll modes
createklllists BToPiEE SllSeq      "B+ -> pi+ e+ e-"         "ChargedTracks XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createklllists BToPi0EE SllSeq     "B0 -> pi0 e+ e-"         "pi0DefaultMass XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createklllists BToPiPi0EE SllSeq   "B+ -> pi+ pi0 e+ e-"     "ChargedTracks pi0DefaultMass XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createklllists BToPiPiEE SllSeq    "B0 -> pi+ pi- e+ e-"     "ChargedTracks ChargedTracks XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"
createklllists BToPiPiPi0EE SllSeq "B0 -> pi+ pi- pi0 e+ e-" "ChargedTracks ChargedTracks pi0DefaultMass XslleBremRecoPidHllMerge XslleBremRecoPidHllMerge"

createklllists BToPiMuMu SllSeq      "B+ -> pi+ mu+ mu-"         "ChargedTracks XsllMuList XsllMuList"
createklllists BToPi0MuMu SllSeq     "B0 -> pi0 mu+ mu-"         "pi0DefaultMass XsllMuList XsllMuList"
createklllists BToPiPi0MuMu SllSeq   "B+ -> pi+ pi0 mu+ mu-"     "ChargedTracks pi0DefaultMass XsllMuList XsllMuList"
createklllists BToPiPiMuMu SllSeq    "B0 -> pi+ pi- mu+ mu-"     "ChargedTracks ChargedTracks XsllMuList XsllMuList"
createklllists BToPiPiPi0MuMu SllSeq "B0 -> pi+ pi- pi0 mu+ mu-" "ChargedTracks ChargedTracks pi0DefaultMass XsllMuList XsllMuList"

############For Daughter UsrData
DaughterLister  BToKsMuMu SllSeq    "XsllKsList XsllDauMuList XsllDauMuList"
DaughterLister  BToKMuMu SllSeq     "XsllKList XsllDauMuList XsllDauMuList"
DaughterLister  BToKsEE SllSeq      "XsllKsList XsllEList XsllEList"
DaughterLister  BToKEE SllSeq       "XsllKList XsllEList XsllEList"

DaughterLister  BToKsPi0MuMu SllSeq    "XsllKsList XsllPi0List XsllDauMuList XsllDauMuList"
DaughterLister  BToKPi0MuMu SllSeq     "XsllKList XsllPi0List XsllDauMuList XsllDauMuList"
DaughterLister  BToKsPiMuMu SllSeq     "XsllKsList XsllPiList XsllDauMuList XsllDauMuList"
DaughterLister  BToKPiMuMu SllSeq      "XsllKList XsllPiList XsllDauMuList XsllDauMuList"
DaughterLister  BToKsPi0EE SllSeq      "XsllKsList XsllPi0List XsllEList XsllEList"
DaughterLister  BToKPi0EE SllSeq       "XsllKList XsllPi0List XsllEList XsllEList"
DaughterLister  BToKsPiEE SllSeq       "XsllKsList XsllPiList XsllEList XsllEList"
DaughterLister  BToKPiEE SllSeq        "XsllKList XsllPiList XsllEList XsllEList"

DaughterLister  BToKsPiPi0MuMu SllSeq    "XsllKsList XsllPiList XsllPi0List XsllDauMuList XsllDauMuList"
DaughterLister  BToKPiPi0MuMu SllSeq     "XsllKList XsllPiList XsllPi0List XsllDauMuList XsllDauMuList"
DaughterLister  BToKsPiPiMuMu SllSeq     "XsllKsList XsllPiList XsllPiList XsllDauMuList XsllDauMuList"
DaughterLister  BToKPiPiMuMu SllSeq      "XsllKList XsllPiList XsllPiList XsllDauMuList XsllDauMuList"
DaughterLister  BToKsPiPi0EE SllSeq      "XsllKsList XsllPiList XsllPi0List XsllEList XsllEList"
DaughterLister  BToKPiPi0EE SllSeq       "XsllKList XsllPiList XsllPi0List XsllEList XsllEList"
DaughterLister  BToKsPiPiEE SllSeq       "XsllKsList XsllPiList XsllPiList XsllEList XsllEList"
DaughterLister  BToKPiPiEE SllSeq        "XsllKList XsllPiList XsllPiList XsllEList XsllEList"

DaughterLister  BToKsPiPiPi0MuMu SllSeq    "XsllKsList XsllPiList XsllPiList XsllPi0List XsllDauMuList XsllDauMuList"
DaughterLister  BToKPiPiPi0MuMu SllSeq     "XsllKList XsllPiList XsllPiList XsllPi0List XsllDauMuList XsllDauMuList"
DaughterLister  BToKsPiPiPiMuMu SllSeq     "XsllKsList XsllPiList XsllPiList XsllPiList XsllDauMuList XsllDauMuList"
DaughterLister  BToKPiPiPiMuMu SllSeq      "XsllKList XsllPiList XsllPiList XsllPiList XsllDauMuList XsllDauMuList"
DaughterLister  BToKsPiPiPi0EE SllSeq      "XsllKsList XsllPiList XsllPiList XsllPi0List XsllEList XsllEList"
DaughterLister  BToKPiPiPi0EE SllSeq       "XsllKList XsllPiList XsllPiList XsllPi0List XsllEList XsllEList"
DaughterLister  BToKsPiPiPiEE SllSeq       "XsllKsList XsllPiList XsllPiList XsllPiList XsllEList XsllEList"
DaughterLister  BToKPiPiPiEE SllSeq        "XsllKList XsllPiList XsllPiList XsllPiList XsllEList XsllEList"

DaughterLister  BToKsPiPiPiPi0MuMu SllSeq    "XsllKsList XsllPiList XsllPiList XsllPiList XsllPi0List XsllDauMuList XsllDauMuList"
DaughterLister  BToKPiPiPiPi0MuMu SllSeq     "XsllKList XsllPiList XsllPiList XsllPiList XsllPi0List XsllDauMuList XsllDauMuList"
DaughterLister  BToKsPiPiPiPiMuMu SllSeq     "XsllKsList XsllPiList XsllPiList XsllPiList XsllPiList XsllDauMuList XsllDauMuList"
DaughterLister  BToKPiPiPiPiMuMu SllSeq      "XsllKList XsllPiList XsllPiList XsllPiList XsllPiList XsllDauMuList XsllDauMuList"
DaughterLister  BToKsPiPiPiPi0EE SllSeq      "XsllKsList XsllPiList XsllPiList XsllPiList XsllPi0List XsllEList XsllEList"
DaughterLister  BToKPiPiPiPi0EE SllSeq       "XsllKList XsllPiList XsllPiList XsllPiList XsllPi0List XsllEList XsllEList"
DaughterLister  BToKsPiPiPiPiEE SllSeq       "XsllKsList XsllPiList XsllPiList XsllPiList XsllPiList XsllEList XsllEList"
DaughterLister  BToKPiPiPiPiEE SllSeq        "XsllKList XsllPiList XsllPiList XsllPiList XsllPiList XsllEList XsllEList"

DaughterLister BToPiEE SllSeq      "XsllPiList XsllEList XsllEList"
DaughterLister BToPi0EE SllSeq     "XsllPi0List XsllEList XsllEList"
DaughterLister BToPiPi0EE SllSeq   "XsllPiList XsllPi0List XsllEList XsllEList"
DaughterLister BToPiPiEE SllSeq    "XsllPiList XsllPiList XsllEList XsllEList"
DaughterLister BToPiPiPi0EE SllSeq "XsllPiList XsllPiList XsllPi0List XsllEList XsllEList"

DaughterLister BToPiMuMu SllSeq      "XsllPiList XsllDauMuList XsllDauMuList"
DaughterLister BToPi0MuMu SllSeq     "XsllPi0List XsllDauMuList XsllDauMuList"
DaughterLister BToPiPi0MuMu SllSeq   "XsllPiList XsllPi0List XsllDauMuList XsllDauMuList"
DaughterLister BToPiPiMuMu SllSeq    "XsllPiList XsllPiList XsllDauMuList XsllDauMuList"
DaughterLister BToPiPiPi0MuMu SllSeq "XsllPiList XsllPiList XsllPi0List XsllDauMuList XsllDauMuList"

