# Please see SoftRelTools/HOWTO-GNUmakefile for documentation
# $Id: GNUmakefile,v 1.24 2007/02/19 16:13:19 marchior Exp $
#################################################################
#++ library products                            [build it with 'lib']

LIBREMOVEFILES := 
LIBTMPLFILES := 
LIBDDLORDERED := 

#################################################################
#++ extra binary products       [not in production, build it with extrabin]

EXTRABINS := 

#################################################################
#++ binary products                             [build it with 'bin']

#BINS := SkimTagApp SkimTagWriteApp
#BINCCFILES := SkimTagApp.cc SkimMicroApp.cc SkimTagWriteApp.cc
BINS := 
BINCCFILES :=

#++ Binary rules                 [in production, build it with 'bin']

#$(bindir)SkimTagApp: SkimTagApp.cc 
#$(bindir)SkimMicroApp: SkimMicroApp.cc 
#$(bindir)SkimTagWriteApp: SkimTagWriteApp.cc 

#++ shell script products..                     [build it with 'bin']
BINSCRIPTS := SkimMakeDoc

#################################################################
#++ regression test scripts                     [build it with 'test']

#################################################################
#++ include standard makefile from SoftRelTools.
include SoftRelTools/standard.mk
